<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hand_perception</name>
  <version>0.0.1</version>
  <description>MediaPipe-based hand landmark detection node for ROS 2 Humble</description>
  <maintainer email="jamilchahine26@gmail.com">Jamil Chahine</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>hand_perception_msgs</depend>
  <depend>python3-serial</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
